name: frontend-ci
on:
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/api-client/**"
      - ".github/workflows/frontend-ci.yaml"
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/api-client/**"

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: |
            apps/web/package-lock.json
            package-lock.json

      - name: Install deps (web)
        working-directory: apps/web
        run: npm ci

      - name: Lint
        working-directory: apps/web
        run: npm run lint

      - name: Build
        working-directory: apps/web
        run: npm run build
